import {prices_constructions, prices_expenses_and_revenues} from './MappingPrices';


export const information_mappings_zones_codes = {
    'default': {
        title: 'Information area',
        information: ['Hover over icons to learn more.', 'Hit the question mark icon if you get stuck.']
    },
    'select': {
        title: 'Select',
        information: ['Learn more about the buildings from the city']
    },
    'help': {
        title: 'Help',
        information: ['Stuck? Confused? Click to learn more']
    },
    'grid': {
        title: 'Grid',
        information: ['Switch the grid on/off','It helps you build more precisely']
    },
    'textures':{
        title: 'Textures',
        information: ['Switch the textures on/off','Place some buildings to see the difference']
    },
    'buildings_on': {
        title: 'Buildings',
        information: ['Hide buildings']
    },
    'buildings_off': {
        title: 'Buildings',
        information: ['Show buildings']
    },
    'road': {
        title: 'Road',
        information: [
            'Place two-lane roads','Left-click to place','Right-click to remove)', 
            'Price: ' + prices_constructions['road'] + '$'
        ]
    },
    'pipe': {
        title: 'Pipe',
        information: [
            'Place pipes to build a sewage system for your city', 
            'Price: ' + prices_constructions['pipe'] + '$'
        ]
    },
    'water': {
        title: 'Water',
        information: ['Place water tiles ','Left-click to place','Right-click to remove']
    },
    'shore': {
        title: 'Shore',
        information: ['Place shore tiles to contain the water ','Left-click to place','Right-click to remove']
    },
    'cloud': {
        title: 'Clouds',
        information: ['Switch the clouds on/off for a clear/cloudy sky']
    },
    'tree': {
        title: 'Tree',
        information: ['Place trees of different sizes ','Left-click to place','Right-click to remove']
    },
    'elevate':{
        title: 'EXPERIMENTAL Elevate terrain',
        information: ['Increase the terrain level']
    },
    'residential': {
        title: 'Residential area',
        information: [
            'Construct residential area buildings (houses, apartments,flats) ',
            'Price: ' + prices_constructions['residential'][1] + '$',
            'Revenues: ' + prices_expenses_and_revenues['residential'][1] + '$'
        ]
    },
    'commercial': {
        title: 'Commercial area',
        information: [
            'Construct commercial zones (shops) ',
            'Price: ' + prices_constructions['commercial'][1] + '$',
            'Expenses: ' + prices_expenses_and_revenues['commercial'][1] + '$'
        ]
    },
    'industry': {
        title: 'Industry area',
        information: [
            'Construct industrial zones (factories, offices, farms) ',
            'Price: ' +  + prices_constructions['industry'][1] + '$',
            'Expenses: ' + prices_expenses_and_revenues['industry'][1] + '$'
        ]
    },
    'upgrade': {
        title: 'Upgrade',
        information: ['Upgrade a building']
    },
    'downgrade': {
        title: 'Downgrade',
        information: ['Downgrade a building']
    },
    'buldoze': {
        title: 'Buldoze',
        information: ['Destroy constructed buildings']
    },
    'save': {
        title: 'Save',
        information: ['Save the city to the local storage']
    },
    'load': {
        title: 'Load',
        information: ['Load the city from the local storage']
    },
    'funds':{
        title: 'Funds',
        information: ['How much money you currently own']
    },
    'population':{
        title: 'Population',
        information: ['Current city population']
    },
    'pause': {
        title: 'Pause',
        information: ['Pause the simulation']
    },
    'play': {
        title: 'Play',
        information: ['Play the simulation at the normal speed']
    },
    'fast1': {
        title: 'Fast 1',
        information: ['Increase the simulation speed x2']
    },
    'fast2': {
        title: 'Fast 2',
        information: ['Increase the simulation speed x4']
    },
    'revenues': {
        title: 'Revenues',
        information: ['Generated by residential areas']
    },
    'expenses': {
        title: 'Expenses',
        information: ['Generated by commercial and industrial areas']
    },
    'err_not_enough_funds': {
        title: 'Not enough funds',
        information: ['The building you are trying to create is too expensive']
    },
    'err_load_too_early': {
        title: 'Loading cooldown',
        information: ['Please wait a few seconds before reloading a map']
    },
    'err_load_no_save': {
        title: 'Loading error',
        information: ['There are no saves to be loaded']
    },
    'help_messages': [
        {
            title: 'Help 1/10',
            information: ['Start by building some residential areas (the green square icon)']
        },
        {
            title: 'Help 2/10',
            information: ['Then build some roads and connect your houses']
        },
        {
            title: 'Help 3/10',
            information: ['Build the sewage system by placing pipes.','Make sure they have a connection to a nearby water source.']
        },
        {
            title: 'Help 4/10',
            information: ['Construct commercial and industry areas.']
        },
        {
            title: 'Help 5/10',
            information: ['Watch your funds! Residential areas provide revenues while commercial/industry areas increase expenses.']
        },
        {
            title: 'Help 6/10',
            information: ['Upgrade some of the buildings to improve their stats.']
        },
        {
            title: 'Help 7/10',
            information: ['Place trees and water/shore tiles to customize your city']
        },
        {
            title: 'Help 8/10',
            information: ['Change the speed of the simulation from the top controls if you get bored :)']
        },
        {
            title: 'Help 9/10',
            information: ['Elevate the terrain to add some hills (work in progress)']
        },
        {
            title: 'Help 10/10',
            information: ['Don\'t forget to save your creation. You can load it later if feel like it.']
        }
    ]
}